# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='body',
            field=models.TextField(),
        ),
    ]
