# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20161005_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_repo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
