# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_project_git_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('adding', 'Adding'), ('added', 'Added')], default='added', max_length=10),
            preserve_default=False,
        ),
    ]
