# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('adding', 'Adding'), ('added', 'Added')], default='adding', max_length=10),
        ),
    ]
