# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20161011_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('adding', 'Adding'), ('added', 'Added')], default='added', max_length=10),
        ),
    ]
