# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20161013_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='git_repo_url',
            new_name='repo_url',
        ),
    ]
